### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by robincoello** [akercheval/si#3]
En tu documento
https://docs.google.com/document/d/1-K0fD7VggYoBeeeJRqcQnw3W_9d-RqdDuT5c9MRoZ8E/edit

globales - globals
asignar - set (de asignar)
hacer - do
escojer - switch
inferior - floor
esno - isnan

**Comment by akercheval** [comment]
Cambié:
- "globals a "globales"
- "interr" a "escojer"
  - cada instancia de "suelo" a "inferior"

Decidí no cambiar:
- "set" a "asignar", porque un set es una estructura de datos, y no una función. Creo que dar un verbo como traducción de "set" sería confuso con por esta razón
  - "haz" a "hacer", solo porque "do" es un comando corto, y quiero replicar los largos de los comandes lo mejor que puedo
  - "esnon" a "esno", igual que "haz" y "hacer"

¡Muchas gracias por la ayuda!

**Comment by robincoello** [comment]
De nada, y felicidades, espero que llegue muy lejos 'si'
